export const data = {
  recipes: [
    {
      name: "Spaghetti Carbonara",
      category: "Italian",
      ingredients: [
        { name: "Spaghetti pasta", amount: "200g" },
        { name: "Eggs", amount: "2" },
        { name: "Pancetta or bacon", amount: "150g" },
        { name: "Parmesan cheese", amount: "100g", type: "grated" },
        { name: "Black pepper", amount: "1/2 tsp", type: "ground" },
        { name: "Salt", amount: "to taste" },
      ],
      instructions: [
        "Cook spaghetti according to package instructions until al dente.",
        "In a bowl, whisk together eggs, grated Parmesan cheese, and black pepper.",
        "In a pan, cook diced pancetta or bacon until crispy.",
        "Drain spaghetti and immediately toss with the egg mixture until well coated.",
        "Add cooked pancetta or bacon and toss again.",
        "Serve immediately with additional grated Parmesan cheese and black pepper.",
      ],
    },
    {
      name: "Chicken Tikka Masala",
      category: "Indian",
      ingredients: [
        { name: "Chicken breast", amount: "500g", type: "boneless, skinless" },
        { name: "Yogurt", amount: "200g", type: "plain" },
        { name: "Tomato sauce", amount: "400g", type: "canned" },
        { name: "Onion", amount: "1", type: "large, diced" },
        { name: "Garlic", amount: "3 cloves", type: "minced" },
        { name: "Ginger", amount: "1 inch", type: "fresh, grated" },
        { name: "Garam masala", amount: "2 tsp" },
        { name: "Cumin", amount: "1 tsp", type: "ground" },
        { name: "Coriander", amount: "1 tsp", type: "ground" },
        { name: "Paprika", amount: "1/2 tsp", type: "smoked" },
        { name: "Salt", amount: "1 tsp", type: "to taste" },
        { name: "Butter", amount: "2 tbsp" },
        { name: "Heavy cream", amount: "200ml" },
      ],
      instructions: [
        "Marinate chicken breast in yogurt, garlic, ginger, garam masala, cumin, coriander, paprika, and salt for at least 1 hour.",
        "Grill or bake marinated chicken until cooked through.",
        "In a pan, sauté diced onion until translucent.",
        "Add tomato sauce and simmer for a few minutes.",
        "Stir in heavy cream and cooked chicken pieces.",
        "Simmer until sauce thickens to desired consistency.",
        "Serve hot with rice or naan bread.",
      ],
    },
    {
      name: "Cepelinai (Lithuanian Potato Dumplings)",
      category: "Lithuanian",
      ingredients: [
        { name: "Potatoes", amount: "1 kg", type: "peeled and grated" },
        { name: "Ground pork", amount: "500g" },
        { name: "Onion", amount: "1 large", type: "finely chopped" },
        { name: "Salt", amount: "2 tsp" },
        { name: "Black pepper", amount: "1/2 tsp", type: "ground" },
        { name: "All-purpose flour", amount: "200g" },
        { name: "Sour cream", amount: "250g", type: "for serving" },
        { name: "Bacon bits", amount: "as desired", type: "for garnish" },
        { name: "Butter", amount: "2 tbsp", type: "for garnish" },
      ],
      instructions: [
        "Place grated potatoes in a clean kitchen towel and squeeze out excess moisture.",
        "In a mixing bowl, combine grated potatoes with salt and let sit for 10 minutes.",
        "Meanwhile, prepare the filling by mixing ground pork, chopped onion, salt, and black pepper.",
        "Take a handful of grated potatoes and form a flat pancake in your hand. Place a spoonful of the meat mixture in the center and enclose it with the potato, forming a dumpling.",
        "Bring a large pot of salted water to a boil.",
        "Carefully add the dumplings to the boiling water. Reduce heat to medium-low and simmer for about 20-25 minutes, or until the dumplings float to the surface and are cooked through.",
        "Remove the dumplings with a slotted spoon and drain them on a plate lined with paper towels.",
        "Serve hot with sour cream, bacon bits, and a drizzle of melted butter on top.",
      ],
    },
    {
      name: "Bulviniai Blynai (Potato Pancakes)",
      category: "Lithuanian",
      ingredients: [
        { name: "Potatoes", amount: "1 kg", type: "peeled and grated" },
        { name: "Onion", amount: "1 large", type: "finely chopped" },
        { name: "Eggs", amount: "2" },
        { name: "All-purpose flour", amount: "4 tbsp" },
        { name: "Salt", amount: "1 tsp" },
        { name: "Black pepper", amount: "1/2 tsp", type: "ground" },
        { name: "Vegetable oil", amount: "1/4 cup", type: "for frying" },
        { name: "Sour cream", amount: "for serving" },
        { name: "Applesauce", amount: "for serving" },
      ],
      instructions: [
        "Place grated potatoes in a clean kitchen towel and squeeze out excess moisture.",
        "In a mixing bowl, combine grated potatoes, chopped onion, eggs, flour, salt, and black pepper.",
        "Heat vegetable oil in a large skillet over medium heat.",
        "Drop spoonfuls of the potato mixture into the hot oil, flattening them with the back of the spoon to form pancakes.",
        "Fry until golden brown on both sides, about 3-4 minutes per side.",
        "Remove pancakes from the skillet and drain on paper towels.",
        "Serve hot with sour cream and applesauce on the side.",
      ],
    },
    {
      name: "Balandėliai (Stuffed Cabbage Rolls)",
      category: "Lithuanian",
      ingredients: [
        { name: "Cabbage leaves", amount: "1 large head" },
        { name: "Ground pork", amount: "500g" },
        { name: "Rice", amount: "1/2 cup", type: "uncooked" },
        { name: "Onion", amount: "1 large", type: "finely chopped" },
        { name: "Carrot", amount: "1 medium", type: "grated" },
        { name: "Egg", amount: "1" },
        { name: "Salt", amount: "2 tsp" },
        { name: "Black pepper", amount: "1/2 tsp", type: "ground" },
        { name: "Tomato sauce", amount: "2 cups" },
        { name: "Bay leaves", amount: "2" },
        { name: "Water", amount: "2 cups" },
      ],
      instructions: [
        "Blanch cabbage leaves in boiling water for a few minutes until softened. Drain and set aside.",
        "In a mixing bowl, combine ground pork, uncooked rice, chopped onion, grated carrot, egg, salt, and black pepper.",
        "Place a spoonful of the meat mixture onto each cabbage leaf and roll tightly, tucking in the sides as you go.",
        "In a large pot, arrange the cabbage rolls seam side down. Pour tomato sauce over the rolls, add bay leaves, and pour water over the top.",
        "Cover the pot and simmer over low heat for about 1.5 to 2 hours, or until the cabbage rolls are tender and the filling is cooked through.",
        "Serve hot, spooning some tomato sauce over the top of each roll.",
      ],
    },
  ],
};
