export const variables = {
  CATAGORIES: [
    { strCategory: "Beef" },
    { strCategory: "Breakfast" },
    { strCategory: "Chicken" },
    { strCategory: "Dessert" },
    { strCategory: "Goat" },
    { strCategory: "Lamb" },
    { strCategory: "Miscellaneous" },
    { strCategory: "Pasta" },
    { strCategory: "Pork" },
    { strCategory: "Seafood" },
    { strCategory: "Side" },
    { strCategory: "Starter" },
    { strCategory: "Vegan" },
    { strCategory: "Vegetarian" },
    { strCategory: "Soup" },
    { strCategory: "Salad" },
    { strCategory: "Bread" },
    { strCategory: "Pizza" },
    { strCategory: "Sandwich" },
  ],
  API_URL: "http://localhost:4000/",
  SUPER_ROLE: "admin",
};
