export const variables = {
  CATAGORIES: [
    { strCategory: "Beef" },
    { strCategory: "Breakfast" },
    { strCategory: "Chicken" },
    { strCategory: "Dessert" },
    { strCategory: "Goat" },
    { strCategory: "Lamb" },
    { strCategory: "Miscellaneous" },
    { strCategory: "Pasta" },
    { strCategory: "Pork" },
    { strCategory: "Seafood" },
    { strCategory: "Side" },
    { strCategory: "Starter" },
    { strCategory: "Vegan" },
    { strCategory: "Vegetarian" },
    { strCategory: "Soup" },
    { strCategory: "Salad" },
    { strCategory: "Bread" },
    { strCategory: "Pizza" },
    { strCategory: "Sandwich" },
  ],
  API_URL: process.env.REACT_APP_BACKEND_URL,
  SUPER_ROLE: "admin",
};
console.log(process.env.REACT_APP_BACKEND_URL);
